### ISSUE TITLE
Test with React Native Testing Library doesn't work

### ISSUE THREAD

**Issue by hockyy** [coinjar/react-native-wagmi-charts#88]
```
  console.error
    The above error occurred in the <LineChartProvider> component:
    
        at LineChartProvider (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-native-wagmi-charts/lib/commonjs/charts/line/Context.tsx:36:3)
        at View
        at Component (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-native/jest/mockComponent.js:28:18)
        at /Users/hocky/IdeaProjects/ajaib-frontend/node_modules/native-base/lib/commonjs/utils/styled.tsx:5:30
        at Box (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/native-base/lib/commonjs/components/primitives/Box/index.tsx:15:16)
        at Stack (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/native-base/lib/commonjs/components/primitives/Stack/Stack.tsx:34:18)
        at VStack (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/native-base/lib/commonjs/components/primitives/Stack/VStack.tsx:17:25)
        at /Users/hocky/IdeaProjects/ajaib-frontend/src/components/TimeChart.tsx:10:5
        at View
        at Component (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-native/jest/mockComponent.js:28:18)
        at GestureHandlerRootView
        at gestureHandlerRootHOC()
        at $dac019021ac61f1f$export$9f8ac96af4b1b2ae (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/@react-aria/ssr/dist/packages/@react-aria/ssr/src/SSRProvider.tsx:51:13)
        at ToastProvider (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/native-base/lib/commonjs/components/composites/Toast/Toast.tsx:144:33)
        at PortalProvider (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/@react-native-aria/overlays/lib/commonjs/Portal.tsx:27:35)
        at HybridProvider (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/native-base/lib/commonjs/core/hybrid-overlay/HybridProvider.tsx:9:3)
        at ResponsiveQueryProvider (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/native-base/lib/commonjs/utils/useResponsiveQuery/ResponsiveQueryProvider.tsx:20:12)
        at RNCSafeAreaProvider
        at Component (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-native/jest/setup.js:332:22)
        at SafeAreaProvider (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-native-safe-area-context/lib/commonjs/SafeAreaContext.tsx:25:3)
        at Provider (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/native-base/lib/commonjs/utils/createContext.tsx:9:13)
        at NativeBaseProvider (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/native-base/lib/commonjs/core/NativeBaseProvider.tsx:52:5)
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10989:23)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11022:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3662:12)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3683:9)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11855:11)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)


TypeError: (0 , _utils.getDomain) is not a function

    at /Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-native-wagmi-charts/lib/commonjs/charts/line/Context.tsx:47:11
    at mountMemo (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6877:19)
    at Object.useMemo (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7213:16)
    at Object.useMemo (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react/cjs/react.development.js:1532:21)
    at LineChartProvider (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-native-wagmi-charts/lib/commonjs/charts/line/Context.tsx:46:24)
    at renderWithHooks (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6016:18)
    at mountIndeterminateComponent (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8744:13)
    at beginWork (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9966:16)
    at performUnitOfWork (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13800:12)
    at workLoopSync (/Users/hocky/IdeaProjects/ajaib-frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:5)
```

**Comment by cam-shaw** [comment]
@hockyy not sure if you resolved this, but I found that mocking the functions in your jest setup file will resolve the issue. I haven't dug into what's wrong with the repository but this works for now. If you remove the `worklet;` directive in the functions, they seem to work. Perhaps something wrong with the way this repo is setup for reanimated testing? 🤷‍♂️ 


```
jest.mock('react-native-wagmi-charts/lib/commonjs/charts/line/utils', () => {
  return {
    ...jest.requireActual(
      'react-native-wagmi-charts/lib/commonjs/charts/line/utils',
    ),
    getDomain: jest.fn((rows) => {
      const values = rows.map(({value}) => value);
      return [Math.min(...values), Math.max(...values)];
    }),
    lineChartDataPropToArray: jest.fn((dataProp) => {
      if (!dataProp) {
        return [];
      }

      if (Array.isArray(dataProp)) {
        return dataProp;
      }

      const data = [];

      Object.values(dataProp).forEach((dataSet) => {
        if (dataSet) {
          data.push(...dataSet);
        }
      });

      return data;
    }),
  };
});
```
